# Generated by Django 4.2.7 on 2026-03-01 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'full_name',
                    models.CharField(
                        help_text='ФИО сотрудника',
                        max_length=200,
                        verbose_name='Полное имя',
                    ),
                ),
                (
                    'position',
                    models.CharField(
                        help_text='Должность сотрудника',
                        max_length=200,
                        verbose_name='Должность',
                    ),
                ),
                (
                    'hired_at',
                    models.DateField(
                        blank=True,
                        help_text='Дата найма сотрудника',
                        null=True,
                        verbose_name='Дата найма',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
                (
                    'department',
                    models.ForeignKey(
                        help_text='Подразделение сотрудника',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='employees',
                        to='departments.department',
                        verbose_name='Подразделение',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(
                        fields=['full_name'],
                        name='employees_e_full_na_997ac1_idx',
                    ),
                    models.Index(
                        fields=['position'],
                        name='employees_e_positio_bc0128_idx',
                    ),
                    models.Index(
                        fields=['hired_at'],
                        name='employees_e_hired_a_63ccd8_idx',
                    ),
                    models.Index(
                        fields=['department'],
                        name='employees_e_departm_99b42d_idx',
                    ),
                ],
            },
        ),
    ]
