# Generated by Django 4.2.7 on 2026-03-01 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Название подразделения',
                        max_length=200,
                        verbose_name='Название',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
                (
                    'parent',
                    models.ForeignKey(
                        blank=True,
                        help_text='Родительское подразделение (null для корневого)',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='children',
                        to='departments.department',
                        verbose_name='Родительское подразделение',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'indexes': [
                    models.Index(
                        fields=['name'], name='departments_name_33d25b_idx'
                    ),
                    models.Index(
                        fields=['parent'],
                        name='departments_parent__2d4307_idx',
                    ),
                    models.Index(
                        fields=['created_at'],
                        name='departments_created_b41d8c_idx',
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(
                fields=('name', 'parent'),
                name='unique_department_name_per_parent',
            ),
        ),
    ]
